name: Lab06 CI/CD Pipeline

# Тригер: запускати тільки при змінах у теці Lab06/
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Lab06/**' # Запускати, якщо зміни стосуються будь-якого файлу всередині Lab06
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Lab06/**'

jobs:
  build-and-publish-lab06:
    runs-on: ubuntu-latest

    # Вказуємо робочу директорію для всіх кроків
    defaults:
      run:
        working-directory: ./Lab06

    steps:
      # 1. Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Налаштування Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Крок CI: Аналіз коду на відповідність стилю
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # 4. Крок CI: Збирання та тестування проєкту
      - name: Build with Maven
        run: mvn clean package

      # 5. Крок CD: Публікація артефакту
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab06-jar
          # Шлях до артефакту тепер відносний до робочої директорії
          path: target/*.jar